app = "waricoma-wsh-2026"
primary_region = "iad"

[build]
[build.args]
NODE_VERSION = "24.14.0"

[env]
PORT = "8080"
NODE_ENV = "production"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
interval = "10s"
timeout = "100s"
grace_period = "10s"
method = "GET"
path = "/"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 2048
